project:
  type: website
  output-dir: .

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data_analysis.qmd
        text: "Data Analysis"

format:
  html:
    theme: cosmo
    toc: true
    