project:
  type: website
  output-dir: .

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "skill_gap_analysis"
      - href: project4.ipynb
        text: "P4"  

format:
  html:
    theme: cosmo
    toc: true
    