project:
  type: website
  output-dir: "."

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Introduction"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "skill_gap_analysis"
      - href: ML methods.ipynb
        text: "ML methods"  

format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: true
  eval: true
  code-fold: true